# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4

    - name: Resolve packages
      run: xcodebuild -resolvePackageDependencies

    - name: Run Tests
      run: xcodebuild test -scheme TestPresentTCA -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.0'
