# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@v4
    
    - name: Install bundle
      run: bundle install

    - name: Resolve packages
      run: xcodebuild -resolvePackageDependencies

    - name: IDESkipPackagePluginFingerprintValidatation
      run: defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES

    - name: IDESkipMacroFingerprintValidation
      run: defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

    - name: Run Tests
      run: bundle exec fastlane tests
